### ISSUE TITLE
rereport_after should be higher

### ISSUE THREAD

**Issue by drphr4ud** [bn-s/cowrie-abuseipdb-api-plugin#1]
Been testing the plugin on 6 cowrie installs for the past week. Works perfectly alongside the dshield plugin. No issues whatsoever.

One thing I noticed is the proposed default value for **rereport_after** = 6

IMO it should default to 23 or 24. Point 8) of their FAQ says:

_If an IP address is engaging in continuous abuse on your system (like attempting to brute-force SSH), we ask that you report the IP roughly once per day. To prevent duplicate reports being submitted automatically through our API, we limit each account to reporting the same IP once per 15 minutes. After 15 minutes, if the same IP is reported within a 24-hours window with the same comment, a new report is not created. Rather, the timestamp of the original report is updated._ 

A lot of people will not bother editing it and leave on default. Perhaps a default of 24 would be better ?

**Comment by bn-s** [comment]
Thanks for the feedback. I'm glad to hear the plugin is working without any issues for you.

It's a good point you make about the re-report period and I think you're right. I neglected the "we ask that you report the IP roughly once per day" part. I'll have a look at it soon and update the config file.

Of course, feel free to go ahead and submit a pull request on the official Cowrie repository if you wish. I'll happily add a comment in support of merging if you get around to it before me.

**Comment by drphr4ud** [comment]
I just noticed in: 

src/abuseipdb/default.cfg

We already have **rereport_after = 24**

The issue may be better addressed in the cowrie project itself - their current .cfg has the 6 hour value.
